### ISSUE TITLE
Nocache doesn't seem to work in included templates

### ISSUE THREAD

**Issue by cabloo** [ytake/Laravel.Smarty#20]
(Laravel 5)

The `nocache` filter and block tag don't seem to work when including templates. Putting `{$smarty.now nocache}` or `{nocache}{$smarty.now}{/nocache}` in an included template always outputs the time that the template was first run after being modified. NOTE: the same does not apply when adding the `nocache` attribute to the `{include}`.

I have caching on and compile_check enabled.

**Comment by ytake** [comment]
try this: http://www.smarty.net/forums/viewtopic.php?p=60164&sid=958d186ae93ff6ab867512e5055a9cae

**Comment by cabloo** [comment]
@ytake you're right, turns out it's an issue with smarty, not this repo.
