### ISSUE TITLE
Run my views

### ISSUE THREAD

**Issue by MarlonEtiene** [ytake/Laravel.Smarty#21]
Hello,

First I need to say this packge are awesome!

I have  a doubt. All times I change a view I need to do
php artisan ytake:smarty-clear-cache
php artisan ytake:smarty-clear-compiled
php artisan ytake:smarty-optimize

Is this right? I really need to do it all times I change my views or have other way to refresh?

**Comment by ytake** [comment]
Changed config value
```php
'caching' =>  true,
```
or
```php
'force_compile' => false,
```

**Comment by MarlonEtiene** [comment]
Thanks!
