### ISSUE TITLE
Allow all smarty config options

### ISSUE THREAD

**Issue by unstoppablecarl** [ytake/Laravel.Smarty#23]
You currently cannot set all smarty config options through the config file.

There should be a way to directly set smarty properties in this file.
https://github.com/ytake/Laravel.Smarty/blob/master/src/Smarty/SmartyFactory.php#L74

**Comment by likemusic** [comment]
I think its typo, fix here https://github.com/ytake/Laravel.Smarty/pull/27

**Comment by unstoppablecarl** [comment]
This issue is not related to that. The relevant code is here now

https://github.com/ytake/Laravel.Smarty/blob/e5f9575735c76f2c17ceaf67be9e4dce4f9dbd4d/src/Smarty/SmartyFactory.php#L106

There are many more smarty config properties that can be set than are listed here. Including the smarty security policy options.

If I make a pull request with the fixes would you use it?

**Comment by ytake** [comment]
:+1:

**Comment by ytake** [comment]
#29 marged
