### ISSUE TITLE
somethings wrong in laravel6.0

### ISSUE THREAD

**Issue by dkeepersun** [ytake/Laravel.Smarty#64]
notice me don't have function configure in bootstrap/app.php

![image](https://user-images.githubusercontent.com/2715388/69749455-7f29f480-1185-11ea-9df3-a7bc8f59b9bd.png)

and the Error: Fatal error: Uncaught Error: Call to undefined method Illuminate\Foundation\Application::configure() in /Users/dk/workspace/SGame/bootstrap/app.php:46 Stack trace: #0 /Users/dk/workspace/SGame/public/admin/index.php(39): require_once() #1 {main} thrown in /Users/dk/workspace/SGame/bootstrap/app.php on line 46

if i remove it.
![image](https://user-images.githubusercontent.com/2715388/69749498-99fc6900-1185-11ea-95a1-10f2ec580b0e.png)

i will get this error: Fatal error: Uncaught ReflectionException: Class config does not exist in /Users/dk/workspace/SGame/vendor/laravel/framework/src/Illuminate/Container/Container.php:803 Stack trace: #0

**Comment by JayBizzle** [comment]
Those lines are used for installation in Lumen, not Laravel

**Comment by dkeepersun** [comment]
come back again to say thank u
