### ISSUE TITLE
Update from Laravel 5.8 to 6.0 fails, illuminate/view required

### ISSUE THREAD

**Issue by OscarWilde** [ytake/Laravel.Smarty#74]
Hi there,

I'm trying to update an old project but stucked from 5.8 to 6.0. It tells me that illuminate/view is required but that is replaced by Laravel 6.0.x

`- ytake/laravel-smarty 2.5.0 requires illuminate/view 5.5.*|5.6.*|5.7.*|5.8.* -> satisfiable by illuminate/view[v5.5.0, ..., 5.8.x-dev].`
`- ytake/laravel-smarty 2.4.0 requires illuminate/view 5.5.*|5.6.*|5.7.* -> satisfiable by illuminate/view[v5.5.0, ..., 5.7.x-dev].`
`- Only one of these can be installed: illuminate/view[v5.5.0, ..., 5.8.x-dev], laravel/framework[v6.0.0, ..., v6.0.4]. laravel/framework replaces illuminate/view and thus cannot coexist with it.`

How can I resolve this problem? I thought it is compatible with Laravel 8x as well?

Thanks for any help.

**Comment by JayBizzle** [comment]
I think you need to update your `composer.json` to ...

```
"ytake/laravel-smarty": "^3.0"
```

**Comment by OscarWilde** [comment]
Yeah thank you, that worked for me!
